name: Feature Request
description: Suggest a new feature for ai4s-core
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the problem
      placeholder: "I'm always frustrated when [...]"
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
  - type: input
    id: domain
    attributes:
      label: Scientific domain
      placeholder: Which domain would this benefit?
  - type: textarea
    id: context
    attributes:
      label: Additional context
