"""
Core orchestrator: translates natural language to scientific workflows.
"""

import json
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field, asdict

from .llm_interface import LLMInterface
from .domain import DomainRegistry


@dataclass
class WorkflowStep:
    """A single step in a scientific workflow."""
    tool: str
    command: str
    inputs: Dict[str, Any] = field(default_factory=dict)
    outputs: Dict[str, Any] = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list)
    description: str = ""
    # Optional: auxiliary files generated by this step (e.g., MDP files)
    auxiliary_files: Dict[str, str] = field(default_factory=dict)
    # Optional: error handling strategy
    error_handling: Dict[str, Any] = field(default_factory=dict)


@dataclass
class WorkflowPlan:
    """A complete workflow plan generated from a research query."""
    query: str
    domain: str
    steps: List[WorkflowStep] = field(default_factory=list)
    estimated_compute: Optional[str] = None
    required_software: List[str] = field(default_factory=list)
    validation_checks: List[str] = field(default_factory=list)


class WorkflowOrchestrator:
    """
    Main orchestrator that converts natural language scientific queries
    into structured, executable workflow plans.
    """

    def __init__(
        self,
        llm: Optional[LLMInterface] = None,
        domain_registry: Optional[DomainRegistry] = None,
    ):
        self.llm = llm or LLMInterface()
        self.domains = domain_registry or DomainRegistry()

    def plan(self, query: str, domain_hint: Optional[str] = None, use_mock: bool = False, strategy: str = "auto") -> WorkflowPlan:
        """
        Generate a workflow plan from a natural language query.

        Args:
            query: Natural language description of the scientific problem.
            domain_hint: Optional domain override (e.g., 'molecular_dynamics').
            use_mock: If True, use a mock LLM for testing/demo without API keys.
            strategy: LLM generation strategy - 'auto' (try full, fallback to step_by_step),
                     'full' (single-shot, may truncate), 'step_by_step' (two-phase, slower but complete).

        Returns:
            WorkflowPlan with steps, dependencies, and resource estimates.
        """
        # Step 1: Classify domain if not provided
        if use_mock:
            domain = domain_hint or "molecular_dynamics"
            plan_raw = self._mock_plan(query, domain)
        else:
            domain = domain_hint or self._classify_domain(query)
            domain_context = self.domains.get_context(domain)

            # Choose generation strategy
            if strategy == "auto":
                # Try full plan first, fallback to step_by_step if truncated
                plan_raw = self.llm.generate_plan(query, domain_context)
                if plan_raw.get("_mode") == "outline" or not plan_raw.get("steps"):
                    print("[Orchestrator] Full plan incomplete, switching to step_by_step...")
                    plan_raw = self.llm.generate_plan_step_by_step(query, domain_context)
            elif strategy == "step_by_step":
                plan_raw = self.llm.generate_plan_step_by_step(query, domain_context)
            else:
                plan_raw = self.llm.generate_plan(query, domain_context)

        # Step 2: Parse and validate
        plan = self._parse_plan(query, domain, plan_raw)
        plan = self._validate_plan(plan)

        return plan

    def _mock_plan(self, query: str, domain: str) -> Dict[str, Any]:
        """Generate a realistic mock plan for demo purposes."""
        if domain == "molecular_dynamics":
            return {
                "steps": [
                    {
                        "tool": "wget",
                        "command": "wget https://files.rcsb.org/download/1UBQ.pdb",
                        "inputs": {},
                        "outputs": {"structure": "1UBQ.pdb"},
                        "dependencies": [],
                        "description": "Download ubiquitin structure from PDB",
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx pdb2gmx -f 1UBQ.pdb -o processed.gro -water tip3p -ff amber99sb-ildn",
                        "inputs": {"structure": "1UBQ.pdb"},
                        "outputs": {"structure": "processed.gro", "topology": "topol.top"},
                        "dependencies": ["0"],
                        "description": "Process structure and generate topology",
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx editconf -f processed.gro -o boxed.gro -c -d 1.0 -bt cubic",
                        "inputs": {"structure": "processed.gro"},
                        "outputs": {"structure": "boxed.gro"},
                        "dependencies": ["1"],
                        "description": "Define simulation box",
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx solvate -cp boxed.gro -cs spc216.gro -o solvated.gro -p topol.top",
                        "inputs": {"structure": "boxed.gro", "topology": "topol.top"},
                        "outputs": {"structure": "solvated.gro", "topology": "topol.top"},
                        "dependencies": ["2"],
                        "description": "Add water molecules to box",
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx grompp -f ions.mdp -c solvated.gro -p topol.top -o ions.tpr",
                        "inputs": {"structure": "solvated.gro", "topology": "topol.top"},
                        "outputs": {"tpr": "ions.tpr"},
                        "dependencies": ["3"],
                        "description": "Prepare input for ion addition",
                        "auxiliary_files": {
                            "ions.mdp": """; ions.mdp - preprocessing for genion
integrator  = steep
emtol       = 1000.0
emstep      = 0.01
nsteps       = 5000
nstlist      = 1
coulombtype  = PME
rcoulomb     = 1.0
rvdw         = 1.0
pbc          = xyz
""",
                        },
                    },
                    {
                        "tool": "gmx",
                        "command": "echo 'SOL' | gmx genion -s ions.tpr -o neutralized.gro -p topol.top -pname NA -nname CL -neutral -conc 0.15",
                        "inputs": {"tpr": "ions.tpr", "topology": "topol.top"},
                        "outputs": {"structure": "neutralized.gro", "topology": "topol.top"},
                        "dependencies": ["4"],
                        "description": "Add ions to neutralize and reach 0.15 M NaCl",
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx grompp -f em.mdp -c neutralized.gro -p topol.top -o em.tpr",
                        "inputs": {"structure": "neutralized.gro", "topology": "topol.top"},
                        "outputs": {"tpr": "em.tpr"},
                        "dependencies": ["5"],
                        "description": "Prepare energy minimization input",
                        "auxiliary_files": {
                            "em.mdp": """; em.mdp - energy minimization
integrator  = steep
emtol       = 1000.0
emstep      = 0.01
nsteps       = 50000
nstlist      = 1
coulombtype  = PME
rcoulomb     = 1.0
rvdw         = 1.0
pbc          = xyz
""",
                        },
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx mdrun -deffnm em -v",
                        "inputs": {"tpr": "em.tpr"},
                        "outputs": {"structure": "em.gro", "log": "em.log"},
                        "dependencies": ["6"],
                        "description": "Run energy minimization",
                        "error_handling": {
                            "check_file": "em.gro",
                            "fallback": "Increase nsteps in em.mdp and retry",
                        },
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr",
                        "inputs": {"structure": "em.gro", "topology": "topol.top"},
                        "outputs": {"tpr": "nvt.tpr"},
                        "dependencies": ["7"],
                        "description": "Prepare NVT equilibration input",
                        "auxiliary_files": {
                            "nvt.mdp": """; nvt.mdp - NVT equilibration
define       = -DPOSRES
integrator   = md
dt           = 0.002
nsteps        = 50000
nstxout      = 500
nstvout      = 500
nstenergy    = 500
nstlog       = 500
continuation = no
constraint_algorithm = lincs
constraints  = h-bonds
lincs_iter   = 1
lincs_order  = 4
coulombtype  = PME
rcoulomb     = 1.0
rvdw         = 1.0
DispCorr     = EnerPres
tcoupl       = V-rescale
tc-grps      = Protein Non-Protein
tau_t        = 0.1     0.1
ref_t        = 300     300
pbc          = xyz
""",
                        },
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx mdrun -deffnm nvt -v",
                        "inputs": {"tpr": "nvt.tpr"},
                        "outputs": {"trajectory": "nvt.xtc", "structure": "nvt.gro"},
                        "dependencies": ["8"],
                        "description": "Run NVT equilibration (100 ps)",
                        "error_handling": {
                            "check_file": "nvt.gro",
                            "temperature_target": 300,
                            "temperature_tolerance": 10,
                        },
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr",
                        "inputs": {"structure": "nvt.gro", "topology": "topol.top", "checkpoint": "nvt.cpt"},
                        "outputs": {"tpr": "npt.tpr"},
                        "dependencies": ["9"],
                        "description": "Prepare NPT equilibration input",
                        "auxiliary_files": {
                            "npt.mdp": """; npt.mdp - NPT equilibration
define       = -DPOSRES
integrator   = md
dt           = 0.002
nsteps        = 50000
nstxout      = 500
nstvout      = 500
nstenergy    = 500
nstlog       = 500
continuation = yes
constraint_algorithm = lincs
constraints  = h-bonds
lincs_iter   = 1
lincs_order  = 4
coulombtype  = PME
rcoulomb     = 1.0
rvdw         = 1.0
DispCorr     = EnerPres
tcoupl       = V-rescale
tc-grps      = Protein Non-Protein
tau_t        = 0.1     0.1
ref_t        = 300     300
pcoupl       = Parrinello-Rahman
pcoupltype   = isotropic
tau_p        = 2.0
ref_p        = 1.0
compressibility = 4.5e-5
pbc          = xyz
""",
                        },
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx mdrun -deffnm npt -v",
                        "inputs": {"tpr": "npt.tpr"},
                        "outputs": {"trajectory": "npt.xtc", "structure": "npt.gro"},
                        "dependencies": ["10"],
                        "description": "Run NPT equilibration (100 ps)",
                        "error_handling": {
                            "check_file": "npt.gro",
                            "pressure_target": 1.0,
                            "pressure_tolerance": 5.0,
                            "density_target": 1000,
                            "density_tolerance": 50,
                        },
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md.tpr",
                        "inputs": {"structure": "npt.gro", "topology": "topol.top", "checkpoint": "npt.cpt"},
                        "outputs": {"tpr": "md.tpr"},
                        "dependencies": ["11"],
                        "description": "Prepare production MD input (100 ns)",
                        "auxiliary_files": {
                            "md.mdp": """; md.mdp - production MD run
integrator   = md
dt           = 0.002
nsteps        = 50000000
nstxout      = 5000
nstvout      = 5000
nstenergy    = 5000
nstlog       = 5000
continuation = yes
constraint_algorithm = lincs
constraints  = h-bonds
lincs_iter   = 1
lincs_order  = 4
coulombtype  = PME
rcoulomb     = 1.0
rvdw         = 1.0
DispCorr     = EnerPres
tcoupl       = V-rescale
tc-grps      = Protein Non-Protein
tau_t        = 0.1     0.1
ref_t        = 300     300
pcoupl       = Parrinello-Rahman
pcoupltype   = isotropic
tau_p        = 2.0
ref_p        = 1.0
compressibility = 4.5e-5
pbc          = xyz
""",
                        },
                    },
                    {
                        "tool": "gmx",
                        "command": "gmx mdrun -deffnm md -v",
                        "inputs": {"tpr": "md.tpr"},
                        "outputs": {"trajectory": "md.xtc", "structure": "md.gro", "energy": "md.edr"},
                        "dependencies": ["12"],
                        "description": "Run production MD simulation (100 ns)",
                        "error_handling": {
                            "check_file": "md.gro",
                            "min_simulation_time_ns": 10,
                        },
                    },
                ],
                "estimated_compute": "~12 hours on 8 CPU cores or ~4 hours on 1 GPU (RTX 3090)",
                "required_software": ["GROMACS 2023+", "wget"],
                "validation_checks": [
                    "Energy minimized to < 1000 kJ/mol/nm",
                    "NVT temperature stable at 300 K",
                    "NPT pressure stable at 1 bar",
                    "Density converged to ~1000 kg/m^3 for water",
                    "RMSD stable during production run",
                ],
            }
        elif domain == "density_functional_theory":
            return {
                "steps": [
                    {
                        "tool": "wget",
                        "command": "wget https://materialsproject.org/static/cifs/Si.cif -O Si.cif",
                        "inputs": {},
                        "outputs": {"structure": "Si.cif"},
                        "dependencies": [],
                        "description": "Download silicon structure (diamond cubic)",
                    },
                    {
                        "tool": "cif2cell",
                        "command": "cif2cell Si.cif -p quantum-espresso -o Si.pw.in",
                        "inputs": {"structure": "Si.cif"},
                        "outputs": {"input": "Si.pw.in"},
                        "dependencies": ["0"],
                        "description": "Convert CIF to Quantum ESPRESSO input format",
                    },
                    {
                        "tool": "pw.x",
                        "command": "mpirun -np 8 pw.x -in Si.scf.in > Si.scf.out",
                        "inputs": {"input": "Si.scf.in"},
                        "outputs": {"charge_density": "Si.save/charge-density.dat", "output": "Si.scf.out"},
                        "dependencies": ["1"],
                        "description": "Self-consistent field (SCF) calculation",
                        "auxiliary_files": {
                            "Si.scf.in": """&CONTROL
  calculation = 'scf'
  prefix = 'Si'
  outdir = './tmp/'
  pseudo_dir = './pseudo/'
/
&SYSTEM
  ibrav = 2
  celldm(1) = 10.26
  nat = 2
  ntyp = 1
  ecutwfc = 80
  ecutrho = 320
/
&ELECTRONS
  conv_thr = 1.0d-8
/
ATOMIC_SPECIES
 Si 28.0855 Si.pbe-n-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS alat
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS automatic
 8 8 8 0 0 0
""",
                        },
                    },
                    {
                        "tool": "pw.x",
                        "command": "mpirun -np 8 pw.x -in Si.bands.in > Si.bands.out",
                        "inputs": {"charge_density": "Si.save/charge-density.dat", "input": "Si.bands.in"},
                        "outputs": {"bands": "Si.bands.dat", "output": "Si.bands.out"},
                        "dependencies": ["2"],
                        "description": "Non-SCF band structure calculation along high-symmetry path",
                        "auxiliary_files": {
                            "Si.bands.in": """&CONTROL
  calculation = 'bands'
  prefix = 'Si'
  outdir = './tmp/'
  pseudo_dir = './pseudo/'
/
&SYSTEM
  ibrav = 2
  celldm(1) = 10.26
  nat = 2
  ntyp = 1
  ecutwfc = 80
  ecutrho = 320
/
&ELECTRONS
  conv_thr = 1.0d-8
/
ATOMIC_SPECIES
 Si 28.0855 Si.pbe-n-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS alat
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS crystal_b
 5
  0.000 0.000 0.000 20  ! Gamma
  0.500 0.500 0.000 20  ! X
  0.500 0.750 0.250 20  ! W
  0.375 0.750 0.375 20  ! K
  0.000 0.000 0.000 20  ! Gamma
""",
                        },
                    },
                    {
                        "tool": "bands.x",
                        "command": "bands.x -in Si.bands.pp.in > Si.bands.pp.out",
                        "inputs": {"bands": "Si.bands.dat", "input": "Si.bands.pp.in"},
                        "outputs": {"bands_data": "Si.bands.gnu", "output": "Si.bands.pp.out"},
                        "dependencies": ["3"],
                        "description": "Post-process band structure data",
                        "auxiliary_files": {
                            "Si.bands.pp.in": """&BANDS
  prefix = 'Si'
  outdir = './tmp/'
/
""",
                        },
                    },
                    {
                        "tool": "dos.x",
                        "command": "dos.x -in Si.dos.in > Si.dos.out",
                        "inputs": {"charge_density": "Si.save/charge-density.dat", "input": "Si.dos.in"},
                        "outputs": {"dos": "Si.dos", "output": "Si.dos.out"},
                        "dependencies": ["2"],
                        "description": "Calculate density of states",
                        "auxiliary_files": {
                            "Si.dos.in": """&DOS
  prefix = 'Si'
  outdir = './tmp/'
  fildos = 'Si.dos'
  Emin = -10.0
  Emax = 10.0
  DeltaE = 0.1
/
""",
                        },
                    },
                    {
                        "tool": "gnuplot",
                        "command": "gnuplot plot_bands.gnu",
                        "inputs": {"bands_data": "Si.bands.gnu"},
                        "outputs": {"plot": "Si_bands.png"},
                        "dependencies": ["4"],
                        "description": "Plot band structure",
                        "auxiliary_files": {
                            "plot_bands.gnu": """set terminal pngcairo enhanced size 800,600
set output 'Si_bands.png'
set title 'Silicon Band Structure'
set xlabel 'k-path'
set ylabel 'Energy (eV)'
set yrange [-10:10]
set xtics ('{/Symbol G}' 0, 'X' 1.0, 'W' 1.5, 'L' 2.0, '{/Symbol G}' 2.5)
plot 'Si.bands.gnu' using 1:2 with lines title 'Bands' lw 2
""",
                        },
                    },
                ],
                "estimated_compute": "~30 minutes on 8 CPU cores",
                "required_software": ["Quantum ESPRESSO 7.x", "cif2cell", "gnuplot"],
                "validation_checks": [
                    "SCF converges to < 1e-6 Ry total energy difference",
                    "Band gap matches known value (~1.1 eV for Si, with DFT underestimation)",
                    "DOS integrates to correct number of electrons (8 per Si atom)",
                    "Band path covers high-symmetry points: Gamma-X-W-L-Gamma",
                ],
            }
        elif domain == "quantum_chemistry":
            return self._mock_quantum_chemistry_plan(query)
        elif domain == "bioinformatics":
            return self._mock_bioinformatics_plan(query)
        elif domain == "materials_simulation":
            return self._mock_materials_simulation_plan(query)
        return {
            "steps": [],
            "estimated_compute": "unknown",
            "required_software": [],
            "validation_checks": [],
        }

    def _mock_quantum_chemistry_plan(self, query: str) -> Dict[str, Any]:
        """Mock plan for quantum chemistry (e.g., ORCA, Gaussian)."""
        return {
            "steps": [
                {
                    "tool": "obabel",
                    "command": "obabel -ismi 'c1ccccc1' -oxyz -O benzene.xyz --gen3d",
                    "inputs": {"smiles": "c1ccccc1"},
                    "outputs": {"structure": "benzene.xyz"},
                    "dependencies": [],
                    "description": "Generate 3D structure from SMILES",
                },
                {
                    "tool": "orca",
                    "command": "orca benzene_opt.inp > benzene_opt.out",
                    "inputs": {"structure": "benzene.xyz"},
                    "outputs": {"optimized": "benzene_opt.xyz", "output": "benzene_opt.out"},
                    "dependencies": ["0"],
                    "description": "Geometry optimization with DFT (B3LYP/def2-SVP)",
                    "auxiliary_files": {
                        "benzene_opt.inp": """! B3LYP def2-SVP OPT
* xyz 0 1
C        0.000000    1.390000    0.000000
C       -1.203922    0.695000    0.000000
C       -1.203922   -0.695000    0.000000
C        0.000000   -1.390000    0.000000
C        1.203922   -0.695000    0.000000
C        1.203922    0.695000    0.000000
H        0.000000    2.470000    0.000000
H       -2.139316    1.235000    0.000000
H       -2.139316   -1.235000    0.000000
H        0.000000   -2.470000    0.000000
H        2.139316   -1.235000    0.000000
H        2.139316    1.235000    0.000000
*""",
                    },
                },
                {
                    "tool": "orca",
                    "command": "orca benzene_freq.inp > benzene_freq.out",
                    "inputs": {"optimized": "benzene_opt.xyz"},
                    "outputs": {"frequencies": "benzene_freq.hess", "output": "benzene_freq.out"},
                    "dependencies": ["1"],
                    "description": "Frequency calculation to verify minimum",
                    "auxiliary_files": {
                        "benzene_freq.inp": """! B3LYP def2-SVP FREQ
%pal nprocs 4 end
* xyzfile 0 1 benzene_opt.xyz
*""",
                    },
                },
                {
                    "tool": "orca",
                    "command": "orca benzene_td.inp > benzene_td.out",
                    "inputs": {"optimized": "benzene_opt.xyz"},
                    "outputs": {"spectrum": "benzene_td.dat", "output": "benzene_td.out"},
                    "dependencies": ["1"],
                    "description": "TD-DFT excited states calculation",
                    "auxiliary_files": {
                        "benzene_td.inp": """! B3LYP def2-SVP TDA TDDDFT
%tddft
  nroots 5
  maxdim 100
end
* xyzfile 0 1 benzene_opt.xyz
*""",
                    },
                },
            ],
            "estimated_compute": "~2 hours on 4 CPU cores",
            "required_software": ["ORCA 5.0+", "Open Babel"],
            "validation_checks": [
                "Geometry optimization converges (max gradient < 1e-4)",
                "All vibrational frequencies are real (no imaginary modes)",
                "TD-DFT excitation energies are positive",
                "Dipole moment is consistent with molecular symmetry",
            ],
        }

    def _mock_bioinformatics_plan(self, query: str) -> Dict[str, Any]:
        """Mock plan for bioinformatics (e.g., RNA-seq analysis)."""
        return {
            "steps": [
                {
                    "tool": "wget",
                    "command": "wget -O SRR12345678.fastq.gz 'https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos2/sra-pub-run-11/SRR12345678/SRR12345678.1'",
                    "inputs": {},
                    "outputs": {"reads": "SRR12345678.fastq.gz"},
                    "dependencies": [],
                    "description": "Download RNA-seq reads from SRA",
                },
                {
                    "tool": "fastqc",
                    "command": "fastqc SRR12345678.fastq.gz -o qc/",
                    "inputs": {"reads": "SRR12345678.fastq.gz"},
                    "outputs": {"qc_report": "qc/SRR12345678_fastqc.html"},
                    "dependencies": ["0"],
                    "description": "Quality control of raw reads",
                },
                {
                    "tool": "trimmomatic",
                    "command": "trimmomatic SE -phred33 SRR12345678.fastq.gz SRR12345678_trimmed.fastq.gz ILLUMINACLIP:TruSeq3-SE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36",
                    "inputs": {"reads": "SRR12345678.fastq.gz"},
                    "outputs": {"trimmed": "SRR12345678_trimmed.fastq.gz"},
                    "dependencies": ["1"],
                    "description": "Trim low-quality bases and adapters",
                    "error_handling": {
                        "check_file": "SRR12345678_trimmed.fastq.gz",
                        "min_size_mb": 0.1,
                    },
                },
                {
                    "tool": "hisat2",
                    "command": "hisat2 -x genome_index -U SRR12345678_trimmed.fastq.gz -S aligned.sam --summary-file hisat2_summary.txt",
                    "inputs": {"trimmed": "SRR12345678_trimmed.fastq.gz"},
                    "outputs": {"alignment": "aligned.sam", "summary": "hisat2_summary.txt"},
                    "dependencies": ["2"],
                    "description": "Align reads to reference genome",
                    "error_handling": {
                        "check_file": "aligned.sam",
                        "min_alignment_rate": 0.7,
                    },
                },
                {
                    "tool": "samtools",
                    "command": "samtools sort aligned.sam -o aligned.bam && samtools index aligned.bam",
                    "inputs": {"alignment": "aligned.sam"},
                    "outputs": {"sorted_bam": "aligned.bam", "index": "aligned.bam.bai"},
                    "dependencies": ["3"],
                    "description": "Sort and index BAM file",
                },
                {
                    "tool": "featureCounts",
                    "command": "featureCounts -T 4 -a annotation.gtf -o counts.txt aligned.bam",
                    "inputs": {"sorted_bam": "aligned.bam"},
                    "outputs": {"counts": "counts.txt"},
                    "dependencies": ["4"],
                    "description": "Count reads per gene",
                    "error_handling": {
                        "check_file": "counts.txt",
                        "min_genes_detected": 10000,
                    },
                },
                {
                    "tool": "R",
                    "command": "Rscript deseq2_analysis.R",
                    "inputs": {"counts": "counts.txt"},
                    "outputs": {"results": "deseq2_results.csv", "plots": "volcano_plot.png"},
                    "dependencies": ["5"],
                    "description": "Differential expression analysis with DESeq2",
                    "auxiliary_files": {
                        "deseq2_analysis.R": """library(DESeq2)
# Load count data
countData <- read.table('counts.txt', header=TRUE, row.names=1, comment.char='#')
colData <- data.frame(condition=factor(c('control','treatment')))
rownames(colData) <- colnames(countData)

# Create DESeq2 dataset
dds <- DESeqDataSetFromMatrix(countData=countData, colData=colData, design=~condition)

# Run analysis
dds <- DESeq(dds)
res <- results(dds)

# Save results
write.csv(as.data.frame(res), file='deseq2_results.csv')

# Volcano plot
pdf('volcano_plot.pdf')
plot(res$log2FoldChange, -log10(res$pvalue), pch=20, col='grey',
     xlab='log2 Fold Change', ylab='-log10 p-value',
     main='Volcano Plot')
points(res$log2FoldChange[res$padj < 0.05], -log10(res$pvalue)[res$padj < 0.05], pch=20, col='red')
dev.off()
""",
                    },
                },
            ],
            "estimated_compute": "~4 hours on 4 CPU cores",
            "required_software": ["FastQC", "Trimmomatic", "HISAT2", "SAMtools", "featureCounts", "R + DESeq2"],
            "validation_checks": [
                "FastQC shows >90% reads with Q30+",
                "Alignment rate >70%",
                ">10,000 genes detected",
                "DESeq2 p-value distribution is uniform under null",
                "Known housekeeping genes show stable expression",
            ],
        }

    def _mock_materials_simulation_plan(self, query: str) -> Dict[str, Any]:
        """Mock plan for materials simulation (e.g., LAMMPS)."""
        return {
            "steps": [
                {
                    "tool": "atomsk",
                    "command": "atomsk --create fcc 4.05 Al al_supercell.xyz -dup 5 5 5",
                    "inputs": {},
                    "outputs": {"structure": "al_supercell.xyz"},
                    "dependencies": [],
                    "description": "Create FCC aluminum supercell (5x5x5, 500 atoms)",
                },
                {
                    "tool": "atomsk",
                    "command": "atomsk al_supercell.xyz lammps",
                    "inputs": {"structure": "al_supercell.xyz"},
                    "outputs": {"data_file": "al_supercell.lmp"},
                    "dependencies": ["0"],
                    "description": "Convert XYZ to LAMMPS data format",
                },
                {
                    "tool": "lmp",
                    "command": "lmp -in min.in -log min.log",
                    "inputs": {"data_file": "al_supercell.lmp"},
                    "outputs": {"minimized": "al_minimized.lmp", "log": "min.log"},
                    "dependencies": ["1"],
                    "description": "Energy minimization using conjugate gradient",
                    "auxiliary_files": {
                        "min.in": """# Energy minimization
units           metal
atom_style      atomic
boundary        p p p
read_data       al_supercell.lmp
pair_style      eam/alloy
pair_coeff      * * Al_u3.eam.alloy Al
neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes
min_style       cg
minimize        1.0e-10 1.0e-10 10000 100000
write_data      al_minimized.lmp
""",
                    },
                },
                {
                    "tool": "lmp",
                    "command": "lmp -in nvt.in -log nvt.log",
                    "inputs": {"minimized": "al_minimized.lmp"},
                    "outputs": {"equilibrated": "al_nvt.lmp", "trajectory": "nvt.dump", "log": "nvt.log"},
                    "dependencies": ["2"],
                    "description": "NVT equilibration at 300K (50 ps)",
                    "auxiliary_files": {
                        "nvt.in": """# NVT equilibration
units           metal
atom_style      atomic
boundary        p p p
read_data       al_minimized.lmp
pair_style      eam/alloy
pair_coeff      * * Al_u3.eam.alloy Al
neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes
timestep        0.001
velocity        all create 300.0 12345 dist gaussian
fix             1 all nvt temp 300.0 300.0 0.1
thermo          100
thermo_style    custom step temp pe ke etotal press density
run             50000
write_data      al_nvt.lmp
""",
                    },
                },
                {
                    "tool": "lmp",
                    "command": "lmp -in npt.in -log npt.log",
                    "inputs": {"equilibrated": "al_nvt.lmp"},
                    "outputs": {"final": "al_npt.lmp", "trajectory": "npt.dump", "log": "npt.log"},
                    "dependencies": ["3"],
                    "description": "NPT equilibration at 300K, 1 bar (50 ps)",
                    "auxiliary_files": {
                        "npt.in": """# NPT equilibration
units           metal
atom_style      atomic
boundary        p p p
read_data       al_nvt.lmp
pair_style      eam/alloy
pair_coeff      * * Al_u3.eam.alloy Al
neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes
timestep        0.001
fix             1 all npt temp 300.0 300.0 0.1 iso 0.0 0.0 1.0
dump            1 all atom 100 npt.dump
thermo          100
thermo_style    custom step temp pe press density lx ly lz
run             50000
write_data      al_npt.lmp
""",
                    },
                },
                {
                    "tool": "lmp",
                    "command": "lmp -in production.in -log production.log",
                    "inputs": {"final": "al_npt.lmp"},
                    "outputs": {"trajectory": "production.dump", "log": "production.log"},
                    "dependencies": ["4"],
                    "description": "Production run (500 ps, properties sampling)",
                    "auxiliary_files": {
                        "production.in": """# Production run
units           metal
atom_style      atomic
boundary        p p p
read_data       al_npt.lmp
pair_style      eam/alloy
pair_coeff      * * Al_u3.eam.alloy Al
neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes
timestep        0.001
fix             1 all npt temp 300.0 300.0 0.1 iso 0.0 0.0 1.0
dump            1 all custom 100 production.dump id type x y z vx vy vz
thermo          100
thermo_style    custom step temp pe press density
run             500000
""",
                    },
                },
                {
                    "tool": "ovito",
                    "command": "ovito production.dump -o rdf.txt -script compute_rdf.py",
                    "inputs": {"trajectory": "production.dump"},
                    "outputs": {"rdf": "rdf.txt"},
                    "dependencies": ["5"],
                    "description": "Compute radial distribution function (RDF)",
                    "auxiliary_files": {
                        "compute_rdf.py": """from ovito.io import import_file
from ovito.modifiers import CoordinationAnalysisModifier

pipeline = import_file("production.dump")
modifier = CoordinationAnalysisModifier(cutoff=5.0, number_of_bins=100)
pipeline.modifiers.append(modifier)

# Export RDF data
for frame in range(pipeline.source.num_frames):
    data = pipeline.compute(frame)
    rdf = data.tables['coordination-rdf']
    with open('rdf.txt', 'a') as f:
        for i in range(len(rdf.x)):
            f.write(f"{rdf.x[i]} {rdf.y[i]}\\n")
""",
                    },
                },
                {
                    "tool": "python",
                    "command": "python3 compute_msd.py",
                    "inputs": {"trajectory": "production.dump"},
                    "outputs": {"msd": "msd.txt", "diffusion": "diffusion_coefficient.txt"},
                    "dependencies": ["5"],
                    "description": "Compute mean squared displacement and diffusion coefficient",
                    "auxiliary_files": {
                        "compute_msd.py": """import numpy as np

# Read dump file and compute MSD
# Simplified: assumes Ovito or MDAnalysis preprocessing
# D = MSD / (6 * t) for 3D

# Placeholder: actual implementation would parse LAMMPS dump
times = np.linspace(0, 500, 100)  # ps
msd = 0.5 * times  # placeholder A^2
D = msd[-1] / (6 * times[-1])  # A^2/ps

np.savetxt('msd.txt', np.column_stack([times, msd]))
with open('diffusion_coefficient.txt', 'w') as f:
    f.write(f"Diffusion coefficient: {D:.4f} A^2/ps = {D*1e-16:.4e} cm^2/s\\n")
""",
                    },
                },
            ],
            "estimated_compute": "~2 hours on 8 CPU cores",
            "required_software": ["LAMMPS", "ATOMSK", "OVITO", "Python3 + NumPy"],
            "validation_checks": [
                "Energy minimization converges (final energy < initial by >10%)",
                "NVT temperature stable at 300 K ± 20 K",
                "NPT density converges to ~2.7 g/cm^3 for aluminum",
                "RDF shows FCC peaks at 2.86, 4.05, 4.96 Å",
                "Diffusion coefficient is positive and physically reasonable",
            ],
        }

    def _classify_domain(self, query: str) -> str:
        """Classify the scientific domain of the query."""
        prompt = f"""Classify the following scientific query into one of these domains:
molecular_dynamics, density_functional_theory, bioinformatics, materials_simulation, quantum_chemistry, other.

Query: {query}

Respond with only the domain name."""
        return self.llm.complete(prompt).strip().lower()

    def _parse_plan(self, query: str, domain: str, raw: Dict[str, Any]) -> WorkflowPlan:
        """Parse LLM output into a structured WorkflowPlan."""
        steps = [
            WorkflowStep(
                tool=s["tool"],
                command=s["command"],
                inputs=s.get("inputs", {}),
                outputs=s.get("outputs", {}),
                dependencies=s.get("dependencies", []),
                description=s.get("description", ""),
                auxiliary_files=s.get("auxiliary_files", {}),
                error_handling=s.get("error_handling", {}),
            )
            for s in raw.get("steps", [])
        ]

        return WorkflowPlan(
            query=query,
            domain=domain,
            steps=steps,
            estimated_compute=raw.get("estimated_compute"),
            required_software=raw.get("required_software", []),
            validation_checks=raw.get("validation_checks", []),
        )

    def _validate_plan(self, plan: WorkflowPlan) -> WorkflowPlan:
        """Validate workflow plan for consistency and completeness."""
        # Check for circular dependencies
        dep_graph = {i: set(step.dependencies) for i, step in enumerate(plan.steps)}
        visited = set()
        rec_stack = set()

        def has_cycle(node: int) -> bool:
            visited.add(node)
            rec_stack.add(node)
            for dep in dep_graph.get(node, set()):
                try:
                    dep_idx = int(dep)
                except ValueError:
                    continue
                if dep_idx not in visited:
                    if has_cycle(dep_idx):
                        return True
                elif dep_idx in rec_stack:
                    return True
            rec_stack.remove(node)
            return False

        for i in range(len(plan.steps)):
            if i not in visited:
                if has_cycle(i):
                    raise ValueError("Workflow plan contains circular dependencies")

        # Check all dependencies reference valid steps
        for i, step in enumerate(plan.steps):
            for dep in step.dependencies:
                try:
                    dep_idx = int(dep)
                except ValueError:
                    continue  # Named dependencies handled at runtime
                if dep_idx < 0 or dep_idx >= len(plan.steps):
                    raise ValueError(
                        f"Step {i} references invalid dependency: {dep}"
                    )

        return plan

    def execute(self, plan: WorkflowPlan, format: str = "python", work_dir: Optional[str] = None) -> str:
        """
        Convert a workflow plan to an executable script and optionally run it.

        This replaces the old `to_script()` method. If you only need the script
        without execution, call with `work_dir=None` (default).

        Args:
            plan: The workflow plan to convert.
            format: Output format - 'python', 'bash', 'snakemake', 'cwl'.
            work_dir: Working directory for execution (if None, scripts are generated but not run).

        Returns:
            Executable script as a string.
        """
        if format == "python":
            script = self._to_python(plan)
        elif format == "bash":
            script = self._to_bash(plan)
        elif format == "snakemake":
            script = self._to_snakemake(plan)
        else:
            raise ValueError(f"Unsupported format: {format}")

        # If work_dir provided, write and optionally execute
        if work_dir:
            import os
            from .executor import WorkflowExecutor, dry_run
            # First do a dry run to show what will happen
            dry_run(plan, work_dir)
            # Then execute
            executor = WorkflowExecutor(use_docker=True, work_dir=work_dir)
            executor.execute_plan(plan)
            executor.save_results(os.path.join(work_dir, "execution_results.json"))

        return script

    # Backward compatibility alias
    to_script = execute

    def _step_to_dict(self, step: WorkflowStep) -> Dict[str, Any]:
        """Convert a WorkflowStep to a plain dict for JSON serialization."""
        return {
            "tool": step.tool,
            "command": step.command,
            "inputs": step.inputs,
            "outputs": step.outputs,
            "dependencies": step.dependencies,
            "description": step.description,
            "auxiliary_files": step.auxiliary_files,
            "error_handling": step.error_handling,
        }

    def _plan_to_dict(self, plan: WorkflowPlan) -> Dict[str, Any]:
        """Convert a WorkflowPlan to a plain dict for JSON serialization."""
        return {
            "query": plan.query,
            "domain": plan.domain,
            "steps": [self._step_to_dict(s) for s in plan.steps],
            "estimated_compute": plan.estimated_compute,
            "required_software": plan.required_software,
            "validation_checks": plan.validation_checks,
        }

    def _to_python(self, plan: WorkflowPlan) -> str:
        """Generate a Python script from the workflow plan."""
        plan_dict = self._plan_to_dict(plan)
        lines = [
            "#!/usr/bin/env python3",
            '"""',
            f"Auto-generated workflow for: {plan.query}",
            f"Domain: {plan.domain}",
            '"""',
            "",
            "import subprocess",
            "import sys",
            "import json",
            "from pathlib import Path",
            "",
            f"WORKFLOW = {json.dumps(plan_dict, indent=4, ensure_ascii=False)}",
            "",
            "def write_auxiliary_files(step):",
            '    """Write auxiliary files (e.g., MDP, input files) for a step."""',
            '    aux = step.get("auxiliary_files", {})',
            '    for filename, content in aux.items():',
            '        Path(filename).write_text(content)',
            '        print(f"  [Written] {filename}")',
            "",
            "def check_error_handling(step, step_idx):",
            '    """Check error handling conditions after a step runs."""',
            '    eh = step.get("error_handling", {})',
            '    if not eh:',
            '        return True',
            '    check_file = eh.get("check_file")',
            '    if check_file and not Path(check_file).exists():',
            '        print(f"  [ERROR] Expected output {check_file} not found")',
            '        fallback = eh.get("fallback")',
            '        if fallback:',
            '            print(f"  [Fallback] {fallback}")',
            '        return False',
            '    return True',
            "",
            "def run_step(step, step_idx):",
            '    print(f"[Step {step_idx}] {step[\'tool\']}: {step[\'description\']}")',
            '    write_auxiliary_files(step)',
            '    cmd = step["command"]',
            '    print(f"  Command: {cmd}")',
            '    try:',
            '        result = subprocess.run(cmd, shell=True, check=True, capture_output=True, text=True)',
            '        print(f"  [OK] Exit code: {result.returncode}")',
            '    except subprocess.CalledProcessError as e:',
            '        print(f"  [ERROR] Command failed with exit code {e.returncode}")',
            '        print(f"  stderr: {e.stderr[:500]}")',
            '        check_error_handling(step, step_idx)',
            '        sys.exit(1)',
            '    check_error_handling(step, step_idx)',
            "",
            "def main():",
        ]

        for i, step in enumerate(plan.steps):
            lines.append(f"    # Step {i}: {step.description}")
            lines.append(f"    run_step(WORKFLOW['steps'][{i}], {i})")
            lines.append("")

        lines.extend([
            'if __name__ == "__main__":',
            "    main()",
            "",
        ])

        return "\n".join(lines)

    def _to_bash(self, plan: WorkflowPlan) -> str:
        """Generate a bash script from the workflow plan."""
        lines = [
            "#!/usr/bin/env bash",
            f"# Auto-generated workflow for: {plan.query}",
            f"# Domain: {plan.domain}",
            "set -euo pipefail",
            "",
            "# Write auxiliary files",
        ]

        # Write all auxiliary files at the top
        for i, step in enumerate(plan.steps):
            for filename, content in step.auxiliary_files.items():
                lines.append(f"# Step {i}: {step.description}")
                lines.append(f"cat > '{filename}' << 'EOF'")
                lines.append(content)
                lines.append("EOF")
                lines.append("")

        lines.append("")
        lines.append("# Run workflow steps")

        for i, step in enumerate(plan.steps):
            lines.append(f"# Step {i}: {step.description}")
            lines.append(f'echo "[Step {i}] {step.tool}: {step.description}"')
            # Add error handling wrapper
            if step.error_handling:
                check_file = step.error_handling.get("check_file")
                if check_file:
                    lines.append(f"if [ ! -f '{check_file}' ]; then")
                    lines.append(f'    echo "[WARNING] Expected output {check_file} not found"')
                    fallback = step.error_handling.get("fallback")
                    if fallback:
                        lines.append(f'    echo "[Fallback] {fallback}"')
                    lines.append("fi")
            lines.append(step.command)
            lines.append("")

        return "\n".join(lines)

    def _to_snakemake(self, plan: WorkflowPlan) -> str:
        """Generate a Snakemake workflow from the plan."""
        lines = [
            f"# Auto-generated Snakemake workflow for: {plan.query}",
            f"# Domain: {plan.domain}",
            "",
        ]

        # Add auxiliary file generation as a rule
        for i, step in enumerate(plan.steps):
            for filename, content in step.auxiliary_files.items():
                aux_rule = f"aux_{i}_{filename.replace('.', '_')}"
                lines.append(f"rule {aux_rule}:")
                lines.append("    output:")
                lines.append(f'        "{filename}"')
                lines.append("    run:")
                lines.append(f'        with open("{filename}", "w") as f:')
                # Escape triple quotes in content
                safe_content = content.replace('"""', '"\"\"')
                lines.append(f'            f.write("""{safe_content}""")')
                lines.append("")

        for i, step in enumerate(plan.steps):
            rule_name = f"step_{i}_{step.tool.replace('-', '_')}"
            lines.append(f"rule {rule_name}:")
            if step.inputs:
                lines.append("    input:")
                for k, v in step.inputs.items():
                    lines.append(f'        {k}="{v}"')
            if step.outputs:
                lines.append("    output:")
                for k, v in step.outputs.items():
                    lines.append(f'        {k}="{v}"')
            lines.append("    shell:")
            # Escape quotes in command
            safe_cmd = step.command.replace('"', '\\"')
            lines.append(f'        "{safe_cmd}"')
            lines.append("")

        return "\n".join(lines)
